In [5]:
Threads.nthreads()

24

In [9]:
Ω = Float32(10.0)
Jz = 1.0f0
Jx = 1.0f0
hz = 1.0f0 
ξ = 2f-1

ag = agtQ(init_nQ(8, 9f-1, 1f0, 50)...)

opt = Flux.Optimiser(WeightDecay(1f-6), Adam(1f-4))

it_MAX = 100
ll_it = zeros(Float32, it_MAX)
println("start!")

st::Int = 0

start!


0

In [19]:
model = Chain(Dense(ag.in_size, ag.n_dense), BatchNorm(ag.n_dense), Dense(ag.n_dense, ag.n_dense, relu), Dense(ag.n_dense, ag.n_dense, relu), Dense(ag.n_dense, ag.n_dense, relu), Dense(ag.n_dense, ag.n_dense, relu), Dense(ag.n_dense, ag.out_size))

Chain(
  Dense(21 => 8),                       # 176 parameters
  BatchNorm(8),                         # 16 parameters, plus 16
  Dense(8 => 8, relu),                  # 72 parameters
  Dense(8 => 8, relu),                  # 72 parameters
  Dense(8 => 8, relu),                  # 72 parameters
  Dense(8 => 8, relu),                  # 72 parameters
  Dense(8 => 16),                       # 144 parameters
)         # Total: 14 trainable arrays, 624 parameters,
          # plus 2 non-trainable, 16 parameters, summarysize 3.477 KiB.

In [56]:
include("TwoSpin_env.jl")
include("TwoSpin_agt.jl")

main (generic function with 1 method)

In [49]:
batch_num = 120
input = zeros(Float32, 5, batch_num)
for i in 1:batch_num
    input[:,i] = generate_parmv(Ω, Jz, Jx, hz, ξ)
end

Kt = zeros(Float32, ag.t_size, 4^2, batch_num)
HF = zeros(Float32, ag.t_size, 4^2, batch_num)

50×16×120 Array{Float32, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.

In [31]:
using BenchmarkTools

In [50]:
for b in 1:batch_num
    Kt[:,:,b], HF[:,:,b] = check_dynamics(model, input[:,b], ag)
end

In [51]:
ll = loss_calc_hyb(model, input, Kt, HF, ag)

880717.2f0

In [52]:
length(σ1)

16

In [53]:
ss = rand(Float32, 16)

16-element Vector{Float32}:
 0.26968545
 0.47865218
 0.6213153
 0.009132981
 0.10004234
 0.69397455
 0.22872466
 0.4433143
 0.64328
 0.61546266
 0.20210987
 0.69507056
 0.43361217
 0.72322786
 0.15992904
 0.65157294

In [54]:
mm = VtoM(ss)

4×4 Hermitian{ComplexF32, Matrix{ComplexF32}}:
   0.269685+0.0im       0.478652-0.621315im  …  0.693975-0.228725im
   0.478652+0.621315im  0.443314+0.0im           0.20211-0.695071im
 0.00913298+0.100042im   0.64328+0.615463im     0.723228-0.159929im
   0.693975+0.228725im   0.20211+0.695071im     0.651573+0.0im

In [57]:
MtoV(mm)

16-element Vector{Float32}:
 0.26968545
 0.47865218
 0.6213153
 0.009132981
 0.10004234
 0.69397455
 0.22872466
 0.4433143
 0.64328
 0.61546266
 0.20210987
 0.69507056
 0.43361217
 0.72322786
 0.15992904
 0.65157294

In [14]:
v = [1,2,3,4,5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [15]:
vv = reshape(v,5,1)

5×1 Matrix{Int64}:
 1
 2
 3
 4
 5

In [16]:
v

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [2]:
a=[zeros(Float32, 4^2) for b in 1:10]

10-element Vector{Vector{Float32}}:
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [8]:
hcat((a)...)

16×10 Matrix{Float32}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [9]:
input = Float32.([10.0, 1.0, 0.7, 0.5, 0.2])

5-element Vector{Float32}:
 10.0
  1.0
  0.7
  0.5
  0.2

In [12]:
using LinearAlgebra

In [17]:
function Ht(input_parm::Vector{Float32}, t::Int, t_size::Int)
    #input_parm = [J_z, J_x, h_z, xi_t]
    H_0 = Hermitian([ -input_parm[2]-2input_parm[4] 0.0f0im 0 -input_parm[3]; 0 input_parm[2] -input_parm[3] 0; 0 -input_parm[3] input_parm[2] 0; -input_parm[3] 0 0 -input_parm[2]+2input_parm[4]])
    V_t = Hermitian([ 0 -1 -1 0; -1 0 0 -1; -1 0 0 -1; 0.0f0im -1 -1 0]*input_parm[5]*sin(Float32(2pi*t/t_size)))
    return (H_0 + V_t)
end

Ht (generic function with 1 method)

In [18]:
@show Ht(input, 1, 100)

Ht(input, 1, 100) = ComplexF32[-2.0f0 + 0.0f0im -0.0125581045f0 + 0.0f0im -0.0125581045f0 + 0.0f0im -0.7f0 + 0.0f0im; -0.0125581045f0 - 0.0f0im 1.0f0 + 0.0f0im -0.7f0 + 0.0f0im -0.0125581045f0 + 0.0f0im; -0.0125581045f0 - 0.0f0im -0.7f0 - 0.0f0im 1.0f0 + 0.0f0im -0.0125581045f0 + 0.0f0im; -0.7f0 - 0.0f0im -0.0125581045f0 - 0.0f0im -0.0125581045f0 - 0.0f0im 0.0f0 + 0.0f0im]


4×4 Hermitian{ComplexF32, Matrix{ComplexF32}}:
       -2.0+0.0im  -0.0125581+0.0im  -0.0125581+0.0im        -0.7+0.0im
 -0.0125581-0.0im         1.0+0.0im        -0.7+0.0im  -0.0125581+0.0im
 -0.0125581-0.0im        -0.7-0.0im         1.0+0.0im  -0.0125581+0.0im
       -0.7-0.0im  -0.0125581-0.0im  -0.0125581-0.0im         0.0+0.0im

In [1]:
using LinearAlgebra

In [4]:
using BenchmarkTools

In [3]:
M = Hermitian(rand(ComplexF32, 4, 4))

4×4 Hermitian{ComplexF32, Matrix{ComplexF32}}:
 0.736373+0.0im        0.155747+0.961568im  …  0.810531+0.0690246im
 0.155747-0.961568im   0.802364+0.0im          0.244744+0.436538im
 0.664029-0.507101im   0.418075-0.87531im      0.289373+0.64866im
 0.810531-0.0690246im  0.244744-0.436538im     0.811453+0.0im

In [5]:
@benchmark exp(1.0f0im*M)

BenchmarkTools.Trial: 10000 samples with 7 evaluations.
 Range (min … max):  5.015 μs … 211.668 μs  ┊ GC (min … max): 0.00% … 95.31%
 Time  (median):     5.493 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   5.648 μs ±   2.920 μs  ┊ GC (mean ± σ):  0.71% ±  1.35%

          ▁▃▅▇▇▇█▅▃▁                                           
  ▁▁▁▂▂▃▄▆███████████▆▆▅▅▅▅▆▅▆▆▆▆▅▆▅▅▄▄▃▃▃▃▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁ ▃
  5.02 μs         Histogram: frequency by time        6.72 μs <

 Memory estimate: 1.66 KiB, allocs estimate: 10.

In [16]:
include("TwoSpin_env.jl")
include("TwoSpin_agt.jl")

main (generic function with 1 method)

In [7]:
en = set_Env(4)
ag = agtQ(init_nQ(["16", "0.01", "0.9", "100"])...)

agtQ(21, 16, 16, 0.01f0, 0.9f0, 100)

In [8]:
opt = Flux.Optimiser(WeightDecay(1f-6), Adam(4f-4))
model = Chain(Dense(ag.in_size, ag.n_dense), BatchNorm(ag.n_dense), Dense(ag.n_dense, ag.n_dense, relu), Dense(ag.n_dense, ag.n_dense, relu), Dense(ag.n_dense, ag.n_dense, relu), Dense(ag.n_dense, ag.n_dense, relu), Dense(ag.n_dense, ag.out_size))

Chain(
  Dense(21 => 16),                      # 352 parameters
  BatchNorm(16),                        # 32 parameters, plus 32
  Dense(16 => 16, relu),                # 272 parameters
  Dense(16 => 16, relu),                # 272 parameters
  Dense(16 => 16, relu),                # 272 parameters
  Dense(16 => 16, relu),                # 272 parameters
  Dense(16 => 16),                      # 272 parameters
)         # Total: 14 trainable arrays, 1_744 parameters,
          # plus 2 non-trainable, 32 parameters, summarysize 7.914 KiB.

In [10]:
batch_num = 5
input = zeros(Float32, 5, batch_num)
for i in 1:batch_num
    input[:,i] = generate_parmv(15.0f0, 1.0f0, 0.7f0, 0.5f0, 0.3f0)
end

Kt = zeros(Float32, ag.t_size, 4^2, batch_num)
HF = zeros(Float32, ag.t_size, 4^2, batch_num)

100×16×5 Array{Float32, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [13]:
@time for b in 1:batch_num
    Kt[:,:,b], HF[:,:,b] = check_dynamics(model, input[:,b],en, ag)
end

  0.122917 seconds (133.25 k allocations: 19.661 MiB)


In [15]:
l_test = loss_calc_hyb(model, input, Kt, HF,en, ag, batch_num)

  0.001030 seconds (1.18 k allocations: 217.469 KiB)
  0.003401 seconds (8.85 k allocations: 1.587 MiB)


221583.58f0

In [18]:
@time ll_it, grads = Flux.withgradient(Flux.params(model)) do
    loss_calc_hyb(model, input, Kt, HF,en, ag, batch_num)
end

 47.526990 seconds (219.24 M allocations: 9.610 GiB, 17.46% gc time, 0.29% compilation time)


(val = 9897.397f0, grad = Grads(...))