In [2]:
findall(x -> x==3, [1, 3, 5])

1-element Vector{Int64}:
 2

In [3]:
findall(x -> x==3, [1, 2, 5])

Int64[]

In [5]:
findmax([1,3,5])[2]

3

In [7]:
a = []
push!(a, 5)

1-element Vector{Any}:
 5

In [9]:
Int(round(5/2))

2

In [10]:
pow(2,3)

UndefVarError: UndefVarError: pow not defined

In [12]:
2^3

8

In [14]:
N=10
a = Array(1, N)

MethodError: MethodError: no method matching Array(::Int64, ::Int64)
Closest candidates are:
  Array(!Matched::LinearAlgebra.UniformScaling, ::Integer, !Matched::Integer) at ~/.julia/juliaup/julia-1.8.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.8/LinearAlgebra/src/uniformscaling.jl:509

In [15]:
vis = zeros(Bool, N)

10-element Vector{Bool}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [16]:
vis[1]

false

In [17]:
A = []
B =[2, 3, 4]
push!(A, B)

1-element Vector{Any}:
 [2, 3, 4]

In [18]:
A

1-element Vector{Any}:
 [2, 3, 4]

In [19]:
A[1]

3-element Vector{Int64}:
 2
 3
 4

In [20]:
v_mat::Vector{Vector{Int}} = []
    for i in 1:N
        t::Vector{Int} = []
        push!(v_mat,t)        
    end

In [21]:
push!(v_mat[3], 5) 

1-element Vector{Int64}:
 5

In [22]:
println(v_mat)

[Int64[], Int64[], [5], Int64[], Int64[], Int64[], Int64[], Int64[], Int64[], Int64[]]


In [23]:
length(v_mat[3])

1

In [25]:
S = "abcdsdfghjkl"
word = S[1:4]

"abcd"

In [26]:
dict = Dict()
dict[word] = 4

4

In [27]:
dict["a"] = 1
dict["b"] = 3


3

In [28]:
dict[word]

4

In [30]:
haskey(dict,"x")

false

In [36]:
Char(1 + 'a')

'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)

In [40]:
findall('d', S)

2-element Vector{Int64}:
 4
 6

In [43]:
aa = [1,2, 3]
prepend!(aa, 0)

4-element Vector{Int64}:
 0
 1
 2
 3

In [44]:
max(1,3)

3