In [10]:
using LinearAlgebra

In [38]:
test_vec = []

Any[]

In [39]:
test_M = [0.0 1.0im; -1.0im 0.0]
push!(test_vec,test_M)
#test_M = Hermitian(test_M)

1-element Vector{Any}:
 ComplexF64[0.0 + 0.0im 0.0 + 1.0im; -0.0 - 1.0im 0.0 + 0.0im]

In [40]:
test_M2 = [1.0 1.0im; -1.0im 1.0]
push!(test_vec,test_M2)

2-element Vector{Any}:
 ComplexF64[0.0 + 0.0im 0.0 + 1.0im; -0.0 - 1.0im 0.0 + 0.0im]
 ComplexF64[1.0 + 0.0im 0.0 + 1.0im; -0.0 - 1.0im 1.0 + 0.0im]

In [62]:
S_test = real.(tr.(test_vec .* (test_M2,)))

2-element Vector{Float64}:
 2.0
 4.0

In [65]:
function generate_M(H_size::Int)
    A::Vector{Hermitian{ComplexF64, Matrix{ComplexF64}}} =[]
    for i in 1:H_size
        for j in i:H_size
            if(i==j)
                #l = 2(d+1-i)*(i-1) + (i-1)^2 + 1
                B = zeros(ComplexF64,H_size,H_size)
                B[i,j] = 1.0
                B = Hermitian(B)
                push!(A,B)
                #A[l,:,:] = B[:,:]
            else
                #l = 2(d+1-i)*(i-1) + (i-1)^2 + 2*(j-i)
                B = zeros(ComplexF64,H_size,H_size)
                B[i,j] = 0.5
                B[j,i] = 0.5
                B = Hermitian(B)
                B2 = zeros(ComplexF64,H_size,H_size)
                B2[i,j] = 0.5im
                B2[j,i] = -0.5im
                B2 = Hermitian(B2)
                #A[l,:,:] = B[:,:]
                #A[l+1,:,:] = B2[:,:]
                push!(A,B)
                push!(A,B2)
            end
        end
    end
    return A
end

generate_Me (generic function with 1 method)

In [66]:
σ_vec = generate_Me(2)

4-element Vector{Hermitian{ComplexF64, Matrix{ComplexF64}}}:
 [1.0 + 0.0im 0.0 + 0.0im; 0.0 - 0.0im 0.0 + 0.0im]
 [0.0 + 0.0im 0.5 + 0.0im; 0.5 - 0.0im 0.0 + 0.0im]
 [0.0 + 0.0im 0.0 + 0.5im; 0.0 - 0.5im 0.0 + 0.0im]
 [0.0 + 0.0im 0.0 + 0.0im; 0.0 - 0.0im 1.0 + 0.0im]

In [67]:
function VtoM(V::Vector{Float64})
    M = V' * σ_vec
    return M
end

VtoM (generic function with 1 method)

In [68]:
V_test = [1.0, 0.0, 2.0, 1.0]
C = VtoM(V_test)

2×2 Hermitian{ComplexF64, Matrix{ComplexF64}}:
 1.0+0.0im  0.0+1.0im
 0.0-1.0im  1.0+0.0im

In [69]:
function MtoV(M::Hermitian{ComplexF64, Matrix{ComplexF64}})
    V = real.(tr.(en.σ_vec .* (M,)))
    return V
end

MtoV (generic function with 1 method)

In [70]:
V_test2 = MtoV(C)

4-element Vector{Float64}:
 1.0
 0.0
 1.0
 1.0

In [1]:
using Flux

In [15]:
model = Chain(RNN(2 => 5), Dense(5 => 1))

Chain(
  Recur(
    RNNCell(2 => 5, tanh),              # 45 parameters
  ),
  Dense(5 => 1),                        # 6 parameters
)         # Total: 6 trainable arrays, 51 parameters,
          # plus 1 non-trainable, 5 parameters, summarysize 580 bytes.

In [18]:
model2 = RNN(2 => 3)

Recur(
  RNNCell(2 => 3, tanh),                # 21 parameters
)         # Total: 4 trainable arrays, 21 parameters,
          # plus 1 non-trainable, 3 parameters, summarysize 316 bytes.

In [41]:
x = rand(Float32, 5)

5-element Vector{Float32}:
 0.016134918
 0.78636706
 0.51258606
 0.60094887
 0.78223944

In [38]:
st0 = 1.0

1.0

In [43]:
y = model2([st0, x[1]])

LoadError: MethodError: no method matching (::Flux.RNNCell{typeof(tanh), Matrix{Float32}, Vector{Float32}, Matrix{Float32}})(::Matrix{Float32}, ::Vector{Float64})
Closest candidates are:
  (::Flux.RNNCell{F, A, V, <:AbstractMatrix{T}})(::Any, ::Union{AbstractVector{T}, AbstractMatrix{T}, Flux.OneHotArray}) where {F, A, V, T} at ~/.julia/packages/Flux/6Q5r4/src/layers/recurrent.jl:138

In [35]:
st0 = model2.state

3×1 Matrix{Float32}:
 -0.2302952
  0.45734346
 -0.04055578

In [34]:
model2.cell(model2.state)

LoadError: MethodError: no method matching (::Flux.RNNCell{typeof(tanh), Matrix{Float32}, Vector{Float32}, Matrix{Float32}})(::Matrix{Float32})
Closest candidates are:
  (::Flux.RNNCell{F, A, V, <:AbstractMatrix{T}})(::Any, ::Union{AbstractVector{T}, AbstractMatrix{T}, Flux.OneHotArray}) where {F, A, V, T} at ~/.julia/packages/Flux/6Q5r4/src/layers/recurrent.jl:138

In [31]:
model2.state, y = model2.cell(model2.state)

LoadError: MethodError: no method matching (::Flux.RNNCell{typeof(tanh), Matrix{Float32}, Vector{Float32}, Matrix{Float32}})(::Matrix{Float32})
Closest candidates are:
  (::Flux.RNNCell{F, A, V, <:AbstractMatrix{T}})(::Any, ::Union{AbstractVector{T}, AbstractMatrix{T}, Flux.OneHotArray}) where {F, A, V, T} at ~/.julia/packages/Flux/6Q5r4/src/layers/recurrent.jl:138