In [10]:
using LinearAlgebra

In [38]:
test_vec = []

Any[]

In [39]:
test_M = [0.0 1.0im; -1.0im 0.0]
push!(test_vec,test_M)
#test_M = Hermitian(test_M)

1-element Vector{Any}:
 ComplexF64[0.0 + 0.0im 0.0 + 1.0im; -0.0 - 1.0im 0.0 + 0.0im]

In [40]:
test_M2 = [1.0 1.0im; -1.0im 1.0]
push!(test_vec,test_M2)

2-element Vector{Any}:
 ComplexF64[0.0 + 0.0im 0.0 + 1.0im; -0.0 - 1.0im 0.0 + 0.0im]
 ComplexF64[1.0 + 0.0im 0.0 + 1.0im; -0.0 - 1.0im 1.0 + 0.0im]

In [62]:
S_test = real.(tr.(test_vec .* (test_M2,)))

2-element Vector{Float64}:
 2.0
 4.0

In [65]:
function generate_M(H_size::Int)
    A::Vector{Hermitian{ComplexF64, Matrix{ComplexF64}}} =[]
    for i in 1:H_size
        for j in i:H_size
            if(i==j)
                #l = 2(d+1-i)*(i-1) + (i-1)^2 + 1
                B = zeros(ComplexF64,H_size,H_size)
                B[i,j] = 1.0
                B = Hermitian(B)
                push!(A,B)
                #A[l,:,:] = B[:,:]
            else
                #l = 2(d+1-i)*(i-1) + (i-1)^2 + 2*(j-i)
                B = zeros(ComplexF64,H_size,H_size)
                B[i,j] = 0.5
                B[j,i] = 0.5
                B = Hermitian(B)
                B2 = zeros(ComplexF64,H_size,H_size)
                B2[i,j] = 0.5im
                B2[j,i] = -0.5im
                B2 = Hermitian(B2)
                #A[l,:,:] = B[:,:]
                #A[l+1,:,:] = B2[:,:]
                push!(A,B)
                push!(A,B2)
            end
        end
    end
    return A
end

generate_Me (generic function with 1 method)

In [66]:
σ_vec = generate_Me(2)

4-element Vector{Hermitian{ComplexF64, Matrix{ComplexF64}}}:
 [1.0 + 0.0im 0.0 + 0.0im; 0.0 - 0.0im 0.0 + 0.0im]
 [0.0 + 0.0im 0.5 + 0.0im; 0.5 - 0.0im 0.0 + 0.0im]
 [0.0 + 0.0im 0.0 + 0.5im; 0.0 - 0.5im 0.0 + 0.0im]
 [0.0 + 0.0im 0.0 + 0.0im; 0.0 - 0.0im 1.0 + 0.0im]

In [67]:
function VtoM(V::Vector{Float64})
    M = V' * σ_vec
    return M
end

VtoM (generic function with 1 method)

In [68]:
V_test = [1.0, 0.0, 2.0, 1.0]
C = VtoM(V_test)

2×2 Hermitian{ComplexF64, Matrix{ComplexF64}}:
 1.0+0.0im  0.0+1.0im
 0.0-1.0im  1.0+0.0im

In [69]:
function MtoV(M::Hermitian{ComplexF64, Matrix{ComplexF64}})
    V = real.(tr.(en.σ_vec .* (M,)))
    return V
end

MtoV (generic function with 1 method)

In [70]:
V_test2 = MtoV(C)

4-element Vector{Float64}:
 1.0
 0.0
 1.0
 1.0