In [1]:
include("AZP_env.jl")

score_test (generic function with 1 method)

In [2]:
function calc_Kt_sym_try(history::Vector{Int}, env::Env)
    MV = []
    his = copy(history)
    t = collect(0:env.Ω*env.dt:2pi)
    #println(length(his))
    for it in 1:length(his)
        sw = pop!(his)
        if(sw==1)
            push!(MV, env.H_0)
        elseif(sw==2)
            push!(MV, env.V_t*sx)
        elseif(sw==3)
            A = pop!(MV)
            B = pop!(MV)
            C = A + B
            push!(MV, C)
        elseif(sw==4)
            A = pop!(MV)
            B = pop!(MV)
            C = -1im*(A*B - B*A)
            push!(MV, C)
        elseif(sw==5)
            A = pop!(MV)
            B = pop!(MV)
            C = (A*B + B*A)/2
            push!(MV, C)
        elseif(sw==6)
            A = pop!(MV)
            S = A.subs(x, t[1])-A.subs(x, t[div(env.t_step,10)])
            if(S==zeros(env.HS_size, env.HS_size))
                B = A
            else
                println("it=$(it): Integral!")
                simplify.(A)
                return A
                B = A.integrate(x)/env.Ω
            end
            push!(MV, B)
        end
        println("it=$(it): $(MV[end])")
    end
    return MV[end]
end

calc_Kt_sym_try (generic function with 1 method)

In [2]:
en = init_Env_quick(["15", "64", "5", "0.25"], Any[0.3, Int(72), 1.0])

Env(15, 200, 2, 3, 1, 6, 90, 64, 7, 5, 1000, 200, 500, 1, 1.0f-5, 0.9f0, 512, 0.3f0, 0.25f0, 0.1f0, 1.0f0, 100, 4, 10.0f0, 0.4f0, 1.0f0, 0.7f0, 0.5f0, ComplexF32[-2.0f0 + 0.0f0im 0.0f0 + 0.0f0im 0.0f0 + 0.0f0im -0.7f0 + 0.0f0im; 0.0f0 - 0.0f0im 1.0f0 + 0.0f0im -0.7f0 + 0.0f0im 0.0f0 + 0.0f0im; 0.0f0 - 0.0f0im -0.7f0 - 0.0f0im 1.0f0 + 0.0f0im 0.0f0 + 0.0f0im; -0.7f0 - 0.0f0im 0.0f0 - 0.0f0im 0.0f0 - 0.0f0im 0.0f0 + 0.0f0im], ComplexF32[0.0f0 + 0.0f0im -0.4f0 + 0.0f0im -0.4f0 + 0.0f0im 0.0f0 + 0.0f0im; -0.4f0 - 0.0f0im 0.0f0 + 0.0f0im 0.0f0 + 0.0f0im -0.4f0 + 0.0f0im; -0.4f0 - 0.0f0im 0.0f0 - 0.0f0im 0.0f0 + 0.0f0im -0.4f0 + 0.0f0im; 0.0f0 - 0.0f0im -0.4f0 - 0.0f0im -0.4f0 - 0.0f0im 0.0f0 + 0.0f0im], 0.0062831854f0, 72, 1.0f0, 1.0f-6)

In [5]:
#hist = [6, 6, 6, 6, 3, 1, 4, 2, 1]
#hist = [6, 6, 6, 3, 2, 6, 5, 1, 5, 2, 6, 4, 2, 1]
hist = [6, 3, 1, 2]
a = calc_Kt_sym(hist, en)

it=1: Sym[0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0; -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); 0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0]
it=2: ComplexF32[-2.0f0 + 0.0f0im 0.0f0 + 0.0f0im 0.0f0 + 0.0f0im -0.7f0 + 0.0f0im; 0.0f0 - 0.0f0im 1.0f0 + 0.0f0im -0.7f0 + 0.0f0im 0.0f0 + 0.0f0im; 0.0f0 - 0.0f0im -0.7f0 - 0.0f0im 1.0f0 + 0.0f0im 0.0f0 + 0.0f0im; -0.7f0 - 0.0f0im 0.0f0 - 0.0f0im 0.0f0 - 0.0f0im 0.0f0 + 0.0f0im]


it=3: Sym[-2.00000000000000 -0.400000005960464*sin(x) -0.400000005960464*sin(x) -0.699999988079071; -0.400000005960464*sin(x) 1.00000000000000 -0.699999988079071 -0.400000005960464*sin(x); -0.400000005960464*sin(x) -0.699999988079071 1.00000000000000 -0.400000005960464*sin(x); -0.699999988079071 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0]
it=4: Integral!
try!Sym[-2.00000000000000 -0.400000005960464*sin(x) -0.400000005960464*sin(x) -0.699999988079071; -0.400000005960464*sin(x) 1.00000000000000 -0.699999988079071 -0.400000005960464*sin(x); -0.400000005960464*sin(x) -0.699999988079071 1.00000000000000 -0.400000005960464*sin(x); -0.699999988079071 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0]
it=4: Sym[-0.2*x 0.0400000005960464*cos(x) 0.0400000005960464*cos(x) -0.0699999988079071*x; 0.0400000005960464*cos(x) 0.1*x -0.0699999988079071*x 0.0400000005960464*cos(x); 0.0400000005960464*cos(x) -0.0699999988079071*x 0.1*x 0.0400000005960464*cos(x); -0.0699999988079071*x 0.0400

(Sym[-0.2*x 0.0400000005960464*cos(x) 0.0400000005960464*cos(x) -0.0699999988079071*x; 0.0400000005960464*cos(x) 0.1*x -0.0699999988079071*x 0.0400000005960464*cos(x); 0.0400000005960464*cos(x) -0.0699999988079071*x 0.1*x 0.0400000005960464*cos(x); -0.0699999988079071*x 0.0400000005960464*cos(x) 0.0400000005960464*cos(x) 0], [0.0, 0.06283185631036758, 0.12566371262073517, 0.18849556893110275, 0.25132742524147034, 0.3141592815518379, 0.3769911378622055, 0.4398229941725731, 0.5026548504829407, 0.5654867067933083  …  5.654867067933083, 5.71769892424345, 5.780530780553818, 5.843362636864185, 5.906194493174553, 5.9690263494849205, 6.031858205795288, 6.094690062105656, 6.157521918416023, 6.220353774726391])

In [8]:
b = sympy.im.(a)

4×4 Matrix{Sym}:
                          0  …                            0
 -0.64000002861023*sin(x)^3     -0.384000017166138*sin(x)^3
 -0.64000002861023*sin(x)^3     -0.384000017166138*sin(x)^3
                          0                               0

In [9]:
c = sympy.re.(a)

4×4 Matrix{Sym}:
                         0  …                          0
 -0.400000005960464*sin(x)     -0.400000005960464*sin(x)
 -0.400000005960464*sin(x)     -0.400000005960464*sin(x)
                         0                             0

In [10]:
d = c.integrate(x) + 1im*b.integrate(x)

4×4 Matrix{Sym}:
                                                                                    0  …                                                                                      0
 I*(-0.213333342870077*cos(x)^3 + 0.64000002861023*cos(x)) + 0.400000005960464*cos(x)     I*(-0.128000005722046*cos(x)^3 + 0.384000017166138*cos(x)) + 0.400000005960464*cos(x)
 I*(-0.213333342870077*cos(x)^3 + 0.64000002861023*cos(x)) + 0.400000005960464*cos(x)     I*(-0.128000005722046*cos(x)^3 + 0.384000017166138*cos(x)) + 0.400000005960464*cos(x)
                                                                                    0                                                                                         0

In [11]:
e = a.integrate(x)

In [15]:
push!(MV, en.H_0)

3-element Vector{Any}:
 Sym[0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0; -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); 0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0]
 Sym[0.320000009536743*sin(x)^2 0 0 0.320000009536743*sin(x)^2; 0 0.320000009536743*sin(x)^2 0.320000009536743*sin(x)^2 0; 0 0.320000009536743*sin(x)^2 0.320000009536743*sin(x)^2 0; 0.320000009536743*sin(x)^2 0 0 0.320000009536743*sin(x)^2]
 ComplexF32[-2.0f0 + 0.0f0im 0.0f0 + 0.0f0im 0.0f0 + 0.0f0im -0.7f0 + 0.0f0im; 0.0f0 - 0.0f0im 1.0f0 + 0.0f0im -0.7f0 + 0.0f0im 0.0f0 + 0.0f0im; 0.0f0 - 0.0f0im -0.7f0 - 0.0f0im 1.0f0 + 0.0f0im 0.0f0 + 0.0f0im; -0.7f0 - 0.0f0im 0.0f0 - 0.0f0im 0.0f0 - 0.0f0im 0.0f0 + 0.0f0im]

In [11]:
push!(MV, en.V_t*sx)
@show MV

MV = Any[Sym[0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0; -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); 0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0], Sym[0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0; -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); 0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0], Sym[0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0; -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); 0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0]]


3-element Vector{Any}:
 Sym[0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0; -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); 0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0]
 Sym[0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0; -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); 0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0]
 Sym[0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0; -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); 0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0]

In [27]:
A = pop!(MV)
B = pop!(MV)
C = A+B
push!(MV, C)

2-element Vector{Any}:
 Sym[0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0; -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); 0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0]
 Sym[0 0.64000002861023*I*sin(x)^3 - 0.400000005960464*sin(x) 0.64000002861023*I*sin(x)^3 - 0.400000005960464*sin(x) 0; -0.64000002861023*I*sin(x)^3 - 0.400000005960464*sin(x) 0 0 -0.384000017166138*I*sin(x)^3 - 0.400000005960464*sin(x); -0.64000002861023*I*sin(x)^3 - 0.400000005960464*sin(x) 0 0 -0.384000017166138*I*sin(x)^3 - 0.400000005960464*sin(x); 0 0.384000017166138*I*sin(x)^3 - 0.400000005960464*sin(x) 0.384000017166138*I*sin(x)^3 - 0.400000005960464*sin(x) 0]

In [16]:
A = pop!(MV)
B = pop!(MV)
C = (A*B + B*A)/2
push!(MV, C)

2-element Vector{Any}:
 Sym[0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0; -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); 0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0]
 Sym[-0.864000021934509*sin(x)^2 0 0 -0.544000012397766*sin(x)^2; 0 0.0960000066757203*sin(x)^2 0.0960000066757203*sin(x)^2 0; 0 0.0960000066757203*sin(x)^2 0.0960000066757203*sin(x)^2 0; -0.544000012397766*sin(x)^2 0 0 -0.224000002861023*sin(x)^2]

In [23]:
A = pop!(MV)
B = pop!(MV)
C = -1im*(A*B - B*A)
push!(MV, C)

2-element Vector{Any}:
 Sym[0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0; -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); 0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0]
 Sym[0 0.64000002861023*I*sin(x)^3 0.64000002861023*I*sin(x)^3 0; -0.64000002861023*I*sin(x)^3 0 0 -0.384000017166138*I*sin(x)^3; -0.64000002861023*I*sin(x)^3 0 0 -0.384000017166138*I*sin(x)^3; 0 0.384000017166138*I*sin(x)^3 0.384000017166138*I*sin(x)^3 0]

In [29]:
@show A = pop!(MV)

A = pop!(MV) = Sym[0 0.64000002861023*I*sin(x)^3 - 0.400000005960464*sin(x) 0.64000002861023*I*sin(x)^3 - 0.400000005960464*sin(x) 0; -0.64000002861023*I*sin(x)^3 - 0.400000005960464*sin(x) 0 0 -0.384000017166138*I*sin(x)^3 - 0.400000005960464*sin(x); -0.64000002861023*I*sin(x)^3 - 0.400000005960464*sin(x) 0 0 -0.384000017166138*I*sin(x)^3 - 0.400000005960464*sin(x); 0 0.384000017166138*I*sin(x)^3 - 0.400000005960464*sin(x) 0.384000017166138*I*sin(x)^3 - 0.400000005960464*sin(x) 0]


4×4 Matrix{Sym}:
                                                       0  …                                                         0
 -0.64000002861023*I*sin(x)^3 - 0.400000005960464*sin(x)     -0.384000017166138*I*sin(x)^3 - 0.400000005960464*sin(x)
 -0.64000002861023*I*sin(x)^3 - 0.400000005960464*sin(x)     -0.384000017166138*I*sin(x)^3 - 0.400000005960464*sin(x)
                                                       0                                                            0

In [30]:
S = A.subs(x, t[1])-A.subs(x, t[div(en.t_step,10)])

4×4 Matrix{Sym}:
                                        0  …                                         0
 0.214330731029275 + 0.0984585273472118*I     0.214330731029275 + 0.0590751164083271*I
 0.214330731029275 + 0.0984585273472118*I     0.214330731029275 + 0.0590751164083271*I
                                        0                                            0

In [31]:
(S==zeros(en.HS_size, en.HS_size))

false

In [32]:
B = A.integrate(x)/en.Ω
#push!(MV, B)

In [5]:
MV = []
t = collect(0:en.Ω*en.dt:2pi)
his = copy(hist)

12-element Vector{Int64}:
 5
 6
 3
 2
 4
 2
 5
 1
 5
 2
 2
 2

In [7]:
typeof(Ks)

Matrix{Sym} (alias for Array{Sym, 2})

In [8]:
K0 = convert(Matrix{ComplexF32}, Ks.subs(x,t[1]))

4×4 Matrix{ComplexF32}:
 0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im

In [9]:
@time Kt = [Hermitian(convert(Matrix{ComplexF32}, Ks.subs(x,t[i]))-K0) for i in 1:en.t_step]
println(Kt[25])

  1.032328 seconds (285.62 k allocations: 17.246 MiB, 10.95% compilation time)


ComplexF32[0.31873837f0 + 0.0f0im 0.0f0 + 0.0f0im 0.0f0 + 0.0f0im 0.31873837f0 - 0.10159414f0im; 0.0f0 - 0.0f0im 0.31873837f0 + 0.0f0im 0.31873837f0 + 0.0f0im 0.0f0 + 0.0f0im; 0.0f0 - 0.0f0im 0.31873837f0 - 0.0f0im 0.31873837f0 + 0.0f0im 0.0f0 + 0.0f0im; 0.31873837f0 + 0.10159414f0im 0.0f0 - 0.0f0im 0.0f0 - 0.0f0im 0.31873837f0 + 0.0f0im]


In [5]:
@time Kt = calc_Kt(hist, en)

it: 1
now: Sym[0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0; -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); 0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0]
it: 2
now: Sym[0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0; -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); 0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0]
it: 3
now: Sym[0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0; -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); -0.400000005960464*sin(x) 0 0 -0.400000005960464*sin(x); 0 -0.400000005960464*sin(x) -0.400000005960464*sin(x) 0]
it: 4
now: Sym[0.320000009536743*sin(x)^2 0 0 0.320000009536743*sin(x)^2; 0 0.320000009536743*sin(x)^2 0.320000009536743*sin(x)^2 0; 0 0.320000009536743*sin(x)^2 0.320000009536743*sin(x)^2 0; 0.320000009536743*sin(x)^2 0 0 0.320000009536743*sin(x)^2]
it: 5
now: ComplexF3

  1.191296 seconds (567.83 k allocations: 31.734 MiB, 18.87% compilation time)


100-element Vector{Hermitian{ComplexF32, Matrix{ComplexF32}}}:
 [0.0f0 + 0.0f0im 0.0f0 + 0.0f0im 0.0f0 + 0.0f0im 0.0f0 + 0.0f0im; 0.0f0 - 0.0f0im 0.0f0 + 0.0f0im 0.0f0 + 0.0f0im 0.0f0 + 0.0f0im; 0.0f0 - 0.0f0im 0.0f0 - 0.0f0im 0.0f0 + 0.0f0im 0.0f0 + 0.0f0im; 0.0f0 - 0.0f0im 0.0f0 - 0.0f0im 0.0f0 - 0.0f0im 0.0f0 + 0.0f0im]
 [0.0012616479f0 + 0.0f0im 0.0f0 + 0.0f0im 0.0f0 + 0.0f0im 0.0012616479f0 - 1.5917556f-6im; 0.0f0 - 0.0f0im 0.0012616479f0 + 0.0f0im 0.0012616479f0 - 4.2351647f-22im 0.0f0 + 0.0f0im; 0.0f0 - 0.0f0im 0.0012616479f0 + 4.2351647f-22im 0.0012616479f0 + 0.0f0im 0.0f0 + 0.0f0im; 0.0012616479f0 + 1.5917556f-6im 0.0f0 - 0.0f0im 0.0f0 - 0.0f0im 0.0012616479f0 + 0.0f0im]
 [0.005026695f0 + 0.0f0im 0.0f0 + 0.0f0im 0.0f0 + 0.0f0im 0.005026695f0 - 2.5267662f-5im; 0.0f0 - 0.0f0im 0.005026695f0 + 0.0f0im 0.005026695f0 + 0.0f0im 0.0f0 + 0.0f0im; 0.0f0 - 0.0f0im 0.005026695f0 - 0.0f0im 0.005026695f0 + 0.0f0im 0.0f0 + 0.0f0im; 0.005026695f0 + 2.5267662f-5im 0.0f0 - 0.0f0im 0.0f0 - 0.0f

In [9]:
@time Hr = calc_Hr(Kt ,en)

  0.005746 seconds (3.97 k allocations: 667.844 KiB)


100-element Vector{Hermitian{ComplexF32, Matrix{ComplexF32}}}:
 [-2.000001f0 + 0.0f0im -0.025116209f0 + 0.0f0im -0.025116209f0 + 0.0f0im -0.700001f0 + 5.192927f-9im; -0.025116209f0 - 0.0f0im 0.999999f0 + 0.0f0im -0.700001f0 + 2.5874165f-9im -0.025116209f0 + 0.0f0im; -0.025116209f0 - 0.0f0im -0.700001f0 - 2.5874165f-9im 0.999999f0 + 0.0f0im -0.025116209f0 + 0.0f0im; -0.700001f0 - 5.192927f-9im -0.025116209f0 - 0.0f0im -0.025116209f0 - 0.0f0im -1.019044f-6 + 0.0f0im]
 [-2.4000058f0 + 0.0f0im -0.050133374f0 + 1.0331404f-10im -0.050133377f0 + 1.0118983f-10im -1.0999987f0 + 0.005535395f0im; -0.050133374f0 - 1.0331404f-10im 0.5999913f0 + 0.0f0im -1.1000087f0 + 0.001001384f0im -0.05013322f0 + 1.01189675f-10im; -0.050133377f0 - 1.0118983f-10im -1.1000087f0 - 0.001001384f0im 0.59999144f0 + 0.0f0im -0.05013323f0 + 1.01189696f-10im; -1.0999987f0 - 0.005535395f0im -0.05013322f0 - 1.01189675f-10im -0.05013323f0 - 1.01189696f-10im -0.4000116f0 + 0.0f0im]
 [-2.7936542f0 + 0.0f0im -0.07495442f0 + 9.54

In [10]:
@time loss = calc_loss(Hr, en)

  0.000114 seconds (299 allocations: 55.766 KiB)


0.40692902f0

In [9]:
@time score = calc_score(hist, en)

history: [5, 6, 3, 2, 4, 2, 5, 1, 5, 2, 2, 2]


  0.970609 seconds (96.49 k allocations: 4.560 MiB, 4.04% compilation time)


0.40692902f0